### PR TITLE
Port to cljc with tests

### PR DESCRIPTION
**Pull request by jiangts**
~~The CLJS build works, except for `Long/MAX_VALUE` and `Long/MIN_VALUE` in `stats`. 
Not exactly sure how to port those.~~

Hope this is helpful! It's my first PR on Github :D

### CODE REVIEW

**Comment by stathissideris** [comment]
This is great, many thanks for taking the time to do this! I had a quick look and I'll do a proper review as soon as possible. One question though: what's your main motivation for wanting spec-provider in cljs? Is it for easy command-line usage via lumo? Or perhaps to create a web app to demonstrate it?

**Comment by gibranrosa** [comment]
@stathissideris I have updated this port to the last commit, and to me the interest in this port is mainly to be able to spec a standalone Electron app in cljs which I am developing, and in the future to use also with lumo.
@jiangts thank you for the initial port

Here is the updated pull #17

**Comment by gibranrosa** [comment]
@stathissideris  It would be desirable if you could review the Pull #17 , because you have made a commit that already create conflicts with this pull, sooner it is, less work to resolve them ;) .

**Comment by stathissideris** [comment]
Hello, yes, I'm fully aware that making changes to master will make it diverge from the pull request and make it harder to merge, but I thought to prioritise supporting Clojure 1.9 now that it's out, instead of getting stuck to a bet version. I will try and review the pull request really soon, but I need some extra time as I'm unfamiliar with cljs testing workflow and I'd like to make sure I can run everything and that the tests pass etc before merging. Thanks for your contribution, and I'd just like to let you know that I'm not ignoring/disregarding it!

**Comment by gibranrosa** [comment]
@stathissideris Sorry for my hastiness, I understand it, and I'll be more patient :) hehe

**Comment by stathissideris** [comment]
Closing this because of #17

**Comment by stathissideris** [comment]
see #17 foe an explanation on why the cljs port is not trivial

**Pull request closed without merging**
