### PR TITLE
Updated @jiangts CLJC port to last commit

### PR DESCRIPTION
**Pull request by gibranrosa**

### CODE REVIEW

**Comment by gibranrosa** [comment]
@stathissideris It would be desirable if you could review this Pull , because you have made a commit that already create conflicts with this pull, sooner it is, less work to resolve them ;) .

**Comment by stathissideris** [comment]
Closing this because the cljs-port branch is more up to date (but still WIP)

**Comment by stathissideris** [comment]
A bit more explanation: the reason branch `cljs-port` is stil in progress is because the unit tests do not pass in cljs, mainly because predicates like `integer?` and `double?` behave very differently in cljs. Aligning those (or even finding a satisfactory behaviour for the cljs port) is not trivial so the port is not ready yet.

**Comment by gibranrosa** [comment]
~~OK, this experience was unhappily very unsatisfactory, when TWO contributions are simply ignored, without even a bit of conversation! Now, this undermines the help from the community and sincerely I hope this changes in the future. 
Even considering this problems, why not put some tests effectively using this PRs, and request changes? 
No! You have simply ignored 2 contributors for your repo!!
Very sad!!!!~~

Edit: Very bad interpretation of mine, sorry! :cry:

**Comment by stathissideris** [comment]
Dude, relax, I just didn't click the "merge pull request" button on github because I wanted to add more commits on my own branch to fix the unit tests and align clj and cljs.

But I did use the pull request as a basis for this, so all your commits can all be seen here:

https://github.com/stathissideris/spec-provider/commits/master

I also acknowledged your contribution in the list of contributors in the readme https://github.com/stathissideris/spec-provider#contributors

AND in the announcement tweet: https://twitter.com/stathissideris/status/990535959505784833

Also this! https://twitter.com/stathissideris/status/990537292170366977

I think I made sure to credit you as much as I could!

**Comment by gibranrosa** [comment]
OK, sorry then! The Github didn't show that, and it wasn't informed in this PR too, the way it was put made me interpret that way, or I am simply too hasty :cry: , anyways, I'm very grateful for the credits! :smiley: and sorry again!

**Comment by stathissideris** [comment]
No problem! Good luck in your open source adventures 😄

**Pull request closed without merging**
