### PR TITLE
Add `bigdec?` support

### PR DESCRIPTION
**Pull request by pfeodrippe**
Address #15

### CODE REVIEW

**Comment by stathissideris** [comment]
That's great thanks for opening this pull request. Could you please add some unit tests demonstrating that this works?

**Comment by pfeodrippe** [comment]
@stathissideris gonna do this today when I get home o/

**Comment by pfeodrippe** [comment]
@stathissideris Need more tests?

**Comment by stathissideris** [comment]
Released in v0.4.10, many thanks!

**Comment by pfeodrippe** [comment]
Thank you! o/
Great library you have here

**Pull request merged**
